### ISSUE TITLE
Current implementation leads to memory leak

### ISSUE THREAD

**Issue by aliostad** [WebApiContrib/WebApiContrib.IoC.CastleWindsor#1]
Castle's child container is a different concept compared to other DI frameworks. So disposing the child container in this case does not do the same as other DIs.

If you add performance counters according to [this](http://docs.castleproject.org/Windsor.Performance-Counters.ashx) you should be able to reproduce memory leak as below:

![windsor-castle](https://f.cloud.github.com/assets/487334/376698/2b181f08-a44e-11e2-8a9e-e116ffecd910.png)

I can send a PR if you are happy.

**Comment by panesofglass** [comment]
@aliostad Would you mind sending a PR?

**Comment by aliostad** [comment]
Yeah, happy to do.

**Comment by aliostad** [comment]
Done.

**Comment by ChrisMissal** [comment]
Closed with commit 4ff9009941afd79d24f07c4055c2e249d7ac6181
